class AppStrings {
  static String appname = "MediApp",
      bestDocapp = "Best Doctor\n Appointment App",
      welcomeBack = "Welcone Back!",
      weAreExcited = "We're excited to have you back!",
      signupNow =
          "Sign up now and start exploring all that our app has to offer.",
      email = "Email",
      emailHint = "Enter your email...",
      password = "Password",
      category = "Category",
      doctor = "Doctor Login",
      settings = "Settings",
      passwordHint = "enter your password here...",
      fullname = "Full Name",
      fullnameHint = "Enter your name here...",
      confirmPassword = "Confirm password",
      forgetPassword = "Forget Password?",
      login = "Login",
      search = "Search doctor",
      signup = "Signup",
      welcome = "Welcome",
      alreadyHaveAccount = "Account have an account?",
      dontHaveAccount = "Don't have an account?",
      body = "Body",
      ear = "Ear",
      liver = "Liver",
      lungs = "Lungs",
      heart = "Heart",
      kidney = "Kidney",
      termsConditions = "Terms & Condition",
      signout = "Signout",
      changePassword = "Change Password";
}
