// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPC6kT8LGoJMout7O6GYEL9lVBwfl2gjM',
    appId: '1:971419893537:web:3b4adf049500eb6c658860',
    messagingSenderId: '971419893537',
    projectId: 'mediapp-4c918',
    authDomain: 'mediapp-4c918.firebaseapp.com',
    storageBucket: 'mediapp-4c918.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1Jk15qmcleRRDeMOJ-7G6WXXCxONfSEY',
    appId: '1:971419893537:android:703e5a295345a177658860',
    messagingSenderId: '971419893537',
    projectId: 'mediapp-4c918',
    storageBucket: 'mediapp-4c918.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAmOzSFLc-5F2rncwwlP9DGb1opXlzp-I',
    appId: '1:971419893537:ios:e80ad262d4dd8fd2658860',
    messagingSenderId: '971419893537',
    projectId: 'mediapp-4c918',
    storageBucket: 'mediapp-4c918.appspot.com',
    iosBundleId: 'com.example.mediapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAmOzSFLc-5F2rncwwlP9DGb1opXlzp-I',
    appId: '1:971419893537:ios:92690f13c0a976c0658860',
    messagingSenderId: '971419893537',
    projectId: 'mediapp-4c918',
    storageBucket: 'mediapp-4c918.appspot.com',
    iosBundleId: 'com.example.mediapp.RunnerTests',
  );
}
